name: CI pipeline to run pytest on pull requests

on:
  pull_request:
    branches:
      - staging

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository for workflow access
        uses: actions/checkout@v4

      - name: set up python environment
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: run tests
        run: |
          pytest